### ISSUE TITLE
Switch to new chemspider Api

### ISSUE THREAD

**Issue by EDiLD** [ropensci/webchem#149]
See also http://link.rsc.org/rsps/m/D_8QAfROIGkEzxHS0wOsR_w13XnCK-xkLMNdaI0-slA

Do not disclose new API key here (maybe use a secret variable for tests).

**Comment by price0416** [comment]
Also running into this issue.  Can't use get_csid() or any chemspider stuff because they no longer issue tokens.  I've tried using their new api keys as tokens, but that doesn't work.

**Comment by schymane** [comment]
The old API will be switched off for sure in November.




On Tue, Sep 18, 2018 at 6:39 PM +0200, "Adam Price" <notifications@github.com<mailto:notifications@github.com>> wrote:


Also running into this issue. Can't use get_csid() or any chemspider stuff because they no longer issue tokens. I've tried using their new api keys as tokens, but that doesn't work.

**Comment by EDiLD** [comment]
Contributions welcome! I am currently too busy to implement it...

**Comment by stitam** [comment]
I think I managed to fix the get_csid() function. As mentioned by @RaoulWolf the new approach is query-> POST -> query ID -> GET -> results of query ID. The body was a little tricky to get right, it was important to put the info into a data.frame, not a list, then convert to JSON, then remove the brackets, and then from there httr:POST could handle. For future updates, I found this curl to R converter very useful: https://curl.trillworks.com/#r. Opening a pull request soon, this will be my first ever, so don't be hard on me:)

**Comment by Aariq** [comment]
I think this was resolved with #178 and can be closed.

**Comment by stitam** [comment]
Many of the functions have been updated but these are related to finding identifiers, converting between identifiers, and retrieving simple record details, e.g. molecular mass.

* The function that retrieves extended record details - cs_extcompinfo() - is still not working.
* The function that retrieves predicted chemical properties - cs_prop() - somehow didn't break.

I would like to either fix or delete cs_extcompinfo() and take a closer look at cs_prop() before we close this issue.
